apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-production
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |-
        image:
          tag: 2.4.5-1631965364
        ingress:
          enabled: true
          annotations: {}
          hosts:
            - host: petclinic-production.127.0.0.1.nip.io
              paths:
                - path: /
                  pathType: Prefix
    path: argocd-managed/petclinic
    repoURL: https://github.com/enrico2828/pipeline-config-petclinic.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true